workflows:
    android-workflow:
        name: Android Workflow
        instance_type: linux
        environment:
            # vars:
            #     # Android Keystore environment variables
            #     CM_KEYSTORE: Encrypted(...) # <-- Put your encrypted keystore file here
            #     CM_KEYSTORE_PASSWORD: Encrypted(...) # <-- Put your encrypted keystore password here
            #     CM_KEY_ALIAS_PASSWORD: Encrypted(...) # <-- Put your encrypted keystore alias password here
            #     CM_KEY_ALIAS_USERNAME: Encrypted(...) # <-- Put your encrypted keystore alias username here  
            node: latest
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: develop
                  include: true
                  source: true
        scripts:
            - name: Install npm dependencies
              script: |
                npm install
            - name: Install detox dependencies
              script: |
                brew tap wix/brew
            - name: Install detox-cli
              script: |
                npm install -g detox-cli
            - name: Set Android SDK location
              script: |
                echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
            # - name: Set up keystore
            #   script: |
            #         echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
            #         cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
            #         storePassword=$CM_KEYSTORE_PASSWORD
            #         keyPassword=$CM_KEY_ALIAS_PASSWORD
            #         keyAlias=$CM_KEY_ALIAS_USERNAME
            #         storeFile=/tmp/keystore.keystore
            #         EOF
            - name: Build with Detox
              script: |
                #!/bin/sh
                set -e
                set -x
                detox build -c android.emu.release -l verbose
            - name: Test with Detox
              script: |
                #!/bin/sh
                set -e
                set -x
                detox test -c android.emu.release -l verbose
            - name: Build Android release
              script: |
                cd android
                ./gradlew assembleRelease
        artifacts:
            - android/app/build/outputs/**/*.apk
        publishing:
            email:
                recipients:
                    - user1@example.com
                    - user2@example.com
            google_play:                          # For publishing your Android app to Google Play
                credentials: Encrypted(...)       # <-- Put your Encrypted JSON key file for Google Play service account here
                track: alpha                      # Name of the track: internal, alpha, beta, production